/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.projectEnd.presation;

import br.edu.ifnmg.projectEnd.Client;
import br.edu.ifnmg.projectEnd.percistence.RepositoryClient;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class DisableClient extends javax.swing.JInternalFrame {

    RepositoryClient repository;
    /**
     * Creates new form DisableClient
     */
    public DisableClient() {
        initComponents();
        this.repository = new RepositoryClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        btnDisable = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Disable Client");

        jLabel1.setText("Id:");

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnDisable.setText("Disable");
        btnDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCheck))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(230, 230, 230)
                                .addComponent(btnDisable)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisable)
                    .addComponent(btnCancel))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableActionPerformed
        
        if(!txtId.getText().isEmpty()){
            Client client = new Client();
            client.setId(Integer.parseInt(txtId.getText()));
            client = repository.CheckClientId(client);
            if(client != null){
                if(repository.CheckStatus(Integer.parseInt(txtId.getText())) == true){
                    String consult = "update client set status = 0 where id = " + Integer.parseInt(txtId.getText());
                    repository.Status(consult);
                    txtId.setText("");
                    JOptionPane.showMessageDialog(null, "Disabled!");
                }else{
                    JOptionPane.showMessageDialog(null, "Client is already disable!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Client do not existing!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Required component missing!!!");
        }
            
    }//GEN-LAST:event_btnDisableActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        if(!txtId.getText().isEmpty()){
            Client client = new Client();
            client.setId(Integer.parseInt(txtId.getText()));
            client = repository.CheckClientId(client);
            if(client != null){
                if(repository.CheckStatus(Integer.parseInt(txtId.getText())) == true){
                    JOptionPane.showMessageDialog(null, "Existing Client!");
                }else{
                    JOptionPane.showMessageDialog(null, "Client is already disabled!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Client do not existing!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Required component missing!!!");
        }
    
    }//GEN-LAST:event_btnCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDisable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
