/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.projectEnd.presation;

/**
 *
 * @author Diego
 */
public class IndividualReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form IndividualReport
     */
    public IndividualReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnReportsClient = new javax.swing.JButton();
        btnReportsUser = new javax.swing.JButton();
        btnReportsProvider = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reports");

        btnReportsClient.setText("Reports Client");
        btnReportsClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsClientActionPerformed(evt);
            }
        });

        btnReportsUser.setText("Reports User");
        btnReportsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsUserActionPerformed(evt);
            }
        });

        btnReportsProvider.setText("Reports Provider");
        btnReportsProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsProviderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReportsClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReportsUser)
                        .addGap(28, 28, 28)
                        .addComponent(btnReportsProvider)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportsClient)
                    .addComponent(btnReportsUser)
                    .addComponent(btnReportsProvider))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportsClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsClientActionPerformed
        ReportsClient screen = new ReportsClient();
        this.getParent().add(screen);
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReportsClientActionPerformed

    private void btnReportsProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsProviderActionPerformed
        ReportsProvider screen = new ReportsProvider();
        this.getParent().add(screen);
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReportsProviderActionPerformed

    private void btnReportsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsUserActionPerformed
        ReportsUser screen = new ReportsUser();
        this.getParent().add(screen);
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReportsUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReportsClient;
    private javax.swing.JButton btnReportsProvider;
    private javax.swing.JButton btnReportsUser;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
