/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.projectEnd.presation;

import br.edu.ifnmg.projectEnd.Purchase;
import br.edu.ifnmg.projectEnd.Sale;
import br.edu.ifnmg.projectEnd.percistence.RepositoryPurchase;
import br.edu.ifnmg.projectEnd.percistence.RepositorySale;
import br.edu.ifnmg.projectEnd.percistence.RepositoryUser;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class ReportsUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReportsUser
     */
    public ReportsUser() {
        initComponents();
    }

    public void UpdateTablePurchase(List<Purchase> list){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Id");
        model.addColumn("Value");
        model.addColumn("Date");
        model.addColumn("User");
        
        for(Purchase purchase : list){
            Vector line = new Vector();
            line.add(purchase.getId());
            line.add(purchase.getValue_total());
            line.add(purchase.getDate());
            line.add(purchase.getUser().getUser());
            model.addRow(line);
        }
        
        tblPS.setModel(model);
    }
    
    public void UpdateTableSale(List<Sale> list){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Id");
        model.addColumn("Value");
        model.addColumn("Date");
        model.addColumn("User");
        
        for(Sale sale : list){
            Vector line = new Vector();
            line.add(sale.getId());
            line.add(sale.getValue_total());
            line.add(sale.getDate());
            line.add(sale.getUser().getUser());
            model.addRow(line);
        }
        
        tblPS.setModel(model);
    }
    
    public void TableNull(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Id");
        model.addColumn("Value");
        model.addColumn("Date");
        model.addColumn("User");
        
        Vector line = new Vector();
        line.add("");
        line.add("");
        line.add("");
        line.add("");
        model.addRow(line);
        
        tblPS.setModel(model);
    }
    
    public void PanelPurchase(List<Purchase> list){
        int cont = 0;
        for(Purchase purchase: list){
            cont +=purchase.getValue_total().setScale(2, RoundingMode.DOWN).floatValue();
        }
        panelValueTotal.setText(String.valueOf(cont));
    }
    
    public void PanelSale(List<Sale> list){
        int cont = 0;
        for(Sale sale: list){
            cont +=sale.getValue_total().setScale(2, RoundingMode.DOWN).floatValue();
        }
        panelValueTotal.setText(String.valueOf(cont));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnPrurchase = new javax.swing.JButton();
        btnSale = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPS = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelValueTotal = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reports User");

        jLabel1.setText("Id:");

        btnPrurchase.setText("Purchase");
        btnPrurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrurchaseActionPerformed(evt);
            }
        });

        btnSale.setText("Sale");
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });

        tblPS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Value", "Date", "User"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPS);

        jScrollPane2.setViewportView(panelValueTotal);

        jLabel2.setText("Value Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrurchase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSale))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrurchase)
                    .addComponent(btnSale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrurchaseActionPerformed
        TableNull();
        RepositoryUser repositoryUser = new RepositoryUser();
        RepositoryPurchase repositoryPurchase = new RepositoryPurchase();
        if(!txtId.getText().isEmpty()){
            if(repositoryUser.CheckUserId(Integer.parseInt(txtId.getText())) == true){
                List<Purchase> list = new ArrayList<>();
                list = repositoryPurchase.OpenListId(Integer.parseInt(txtId.getText()), 2);
                UpdateTablePurchase(list);
                PanelPurchase(list);
            }else{
                JOptionPane.showMessageDialog(null, "Client does not exist!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Blank field!");
        }
    }//GEN-LAST:event_btnPrurchaseActionPerformed

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
        TableNull();
        RepositoryUser repositoryUser = new RepositoryUser();
        RepositorySale repositorySale = new RepositorySale();
        if(!txtId.getText().isEmpty()){
            if(repositoryUser.CheckUserId(Integer.parseInt(txtId.getText())) == true){
                List<Sale> list = new ArrayList<>();
                list = repositorySale.OpenListId(Integer.parseInt(txtId.getText()), 2);
                UpdateTableSale(list);
                PanelSale(list);
            }else{
                JOptionPane.showMessageDialog(null, "User does not exist!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Blank field!");
        }
    }//GEN-LAST:event_btnSaleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrurchase;
    private javax.swing.JButton btnSale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane panelValueTotal;
    private javax.swing.JTable tblPS;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
