/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.projectEnd.presation;

import br.edu.ifnmg.projectEnd.Client;
import br.edu.ifnmg.projectEnd.Item;
import br.edu.ifnmg.projectEnd.Product;
import br.edu.ifnmg.projectEnd.Sale;
import br.edu.ifnmg.projectEnd.Stock;
import br.edu.ifnmg.projectEnd.UnitSale;
import br.edu.ifnmg.projectEnd.User;
import br.edu.ifnmg.projectEnd.percistence.RepositoryClient;
import br.edu.ifnmg.projectEnd.percistence.RepositoryProduct;
import br.edu.ifnmg.projectEnd.percistence.RepositorySale;
import br.edu.ifnmg.projectEnd.percistence.RepositoryStock;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class SaleProduct extends javax.swing.JInternalFrame {
  
    private Sale sale;
    private User user;
    /**
     * Creates new form SaleProduct
     */
    public SaleProduct(User user) {
        initComponents();
        this.sale = new Sale();
        this.user = user;
    }

    public void addProduct(Product product)throws Exception{
        Item item = new Item();
        
        item.setAmount(Integer.parseInt(txtAmount.getText()));
        item.setProduct(product);
        item.setValue(product.getSale_price());
        this.sale.addItem(item);
    }
    
    public void setNull(){
        this.txtAmount.setText("");
        this.txtProductId.setText("");
        this.txtProductName.setText("");
    }    
    
    public void addTable(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Product");
        model.addColumn("Amount");
        model.addColumn("Value");
        List<Item> it = this.sale.getItens();
        for(Item item : it){
            Vector line = new Vector();
            line.add(item.getProduct().getName());
            line.add(item.getAmount());
            line.add(item.getValue());
            model.addRow(line);
        }
        
        tblProduct.setModel(model);
    }
    
    public void setNullTable(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Product");
        model.addColumn("Amount");
        model.addColumn("Value");
        
        Vector line = new Vector();
        line.add("");
        line.add("");
        line.add("");
        model.addRow(line);
        
        tblProduct.setModel(model);
    }
    
    public void panelValueTotal(){
        float value = 0;
        for(Item item : this.sale.getItens()){
            value += item.getAmount() * item.getProduct().getSale_price().setScale(2, RoundingMode.DOWN).floatValue();
        }
        panelValueTotal.setText(String.valueOf(value));
    }
    
    public boolean check(Product product){
        RepositoryStock repo = new RepositoryStock();
        int value = 0;
        int amount = 0;
        amount = repo.CheckAmount(product.getId());
        Item et = new Item();
        for(Item item: sale.getItens()){
            if(item.getProduct() == product){
                value += item.getAmount();
                et = item;
            }
        }
        
        if(product.getSale_unit() == UnitSale.Unidade){
            if(value >= amount){
                sale.removeItem(et);
                return false;
            }else{
                return true;
            }
        }
        if(product.getSale_unit() == UnitSale.Conjunto){
            if(value*10 >= amount){
                sale.removeItem(et);
                return false;
            }else{
                return true;
            }
        }
        
        return false;
    }
    
    public void addStock(){
        RepositoryStock repository = new RepositoryStock();
        Stock stock = new Stock();
        for(Item item: sale.getItens()){
            stock.setProduct(item.getProduct());
            if(item.getProduct().getSale_unit() == UnitSale.Unidade){
                stock.setAmount(item.getAmount());
            }
            if(item.getProduct().getSale_unit() == UnitSale.Conjunto){
                stock.setAmount(item.getAmount() * 20);
            }
            if(item.getProduct().getSale_unit() == UnitSale.Caixa){
                stock.setAmount(item.getAmount() * 10);
            }
            repository.Save(stock, 0);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtClientId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelValueTotal = new javax.swing.JEditorPane();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Purchase");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sale");

        jLabel1.setText("Client id:");

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Product id:");

        jLabel3.setText("Product name:");

        jLabel4.setText("Amount:");

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Amount", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(panelValueTotal);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClientId)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAmount))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProductId)
                                .addGap(67, 67, 67)
                                .addComponent(btnAdd)
                                .addGap(34, 34, 34))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCancel)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RepositoryClient repositoryClient = new RepositoryClient();
        Client client = new Client();
        if(!txtClientId.getText().isEmpty()){
            client.setId(Integer.parseInt(txtClientId.getText()));
            if(repositoryClient.CheckClientId(client) != null){
                if(repositoryClient.CheckStatus(client.getId()) == true){
                    JOptionPane.showMessageDialog(null, "Client valid!");
                }else{
                    JOptionPane.showMessageDialog(null, "Client Desable");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Client does not exist ");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Missing component");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        RepositoryProduct repositoryProduct = new RepositoryProduct();
        Product product = new Product();
        try{
            if(!txtProductName.getText().isEmpty() && !txtProductId.getText().isEmpty() && !txtAmount.getText().isEmpty()){
                if(repositoryProduct.CheckProductIdName(Integer.parseInt(txtProductId.getText()), txtProductName.getText()) == false){
                    if(repositoryProduct.CheckStatus(Integer.parseInt(txtProductId.getText())) == true){
                        try{
                           product = repositoryProduct.Open(Integer.parseInt(txtProductId.getText()));
                           addProduct(product);
                           if(check(product) == true){
                               setNull();
                               addTable();
                               panelValueTotal();
                           }else{
                               JOptionPane.showMessageDialog(null, "Falta no estoque ");
                           }
                           
                        }catch(Exception ex){}
                    }else{
                        JOptionPane.showMessageDialog(null, "Product disable ");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Product does not exist ");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Missing components");
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        setNull();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        RepositoryClient repositoryClient = new RepositoryClient();
        RepositoryStock repositoryStock = new RepositoryStock();
        Client client = new Client();
        if(!txtClientId.getText().isEmpty()){
           client.setId(Integer.parseInt(txtClientId.getText()));
            if(repositoryClient.CheckClientId(client) != null){
                if(repositoryClient.CheckStatus(client.getId()) == true){
                    if(sale.getItens() != null){
                        RepositorySale repository = new RepositorySale();
                        client = repositoryClient.Open(Integer.parseInt(txtClientId.getText()));
                        sale.setClient(client);
                        sale.setValue_total(BigDecimal.valueOf(Double.valueOf(panelValueTotal.getText())));
                        sale.setUser(this.user);
                        if(repository.Save(this.sale) == true){
                            addStock();
                            repository.addItem(sale);
                            setNull();
                            JOptionPane.showMessageDialog(null, "Purchase save");
                            txtClientId.setText("");
                            panelValueTotal.setText("");
                            setNullTable();
                        sale = new Sale();
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Client Desable");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Client does not exist ");
            }
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JEditorPane panelValueTotal;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtClientId;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtProductName;
    // End of variables declaration//GEN-END:variables
}
