/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.projectEnd.presation;

import br.edu.ifnmg.projectEnd.Provider;
import br.edu.ifnmg.projectEnd.percistence.RepositoryProvider;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class SearchProvider extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchProvider
     */
    public SearchProvider() {
        initComponents();
    }

    public void addTable(List<Provider> providers){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Name");
        model.addColumn("Id");
        model.addColumn("Cnpj");
        model.addColumn("Email");
        
        for(Provider provider : providers){
            Vector line = new Vector();
            line.add(provider.getName());
            line.add(provider.getId());
            line.add(provider.getCnpj());
            line.add(provider.getEmail());
            
            model.addRow(line);
        }
        
        tblProduct.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnSearchAll = new javax.swing.JButton();
        btnSearchEnable = new javax.swing.JButton();
        btnSearchDisable = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name ", "Id", "Cnpj", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Seache Provider");

        btnSearchAll.setText("Search all");
        btnSearchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllActionPerformed(evt);
            }
        });

        btnSearchEnable.setText("Search enable");
        btnSearchEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEnableActionPerformed(evt);
            }
        });

        btnSearchDisable.setText("Search Disable");
        btnSearchDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDisableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSearchDisable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchEnable)
                        .addGap(89, 89, 89)
                        .addComponent(btnSearchAll)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchAll)
                    .addComponent(btnSearchEnable)
                    .addComponent(btnSearchDisable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllActionPerformed
        try{
            RepositoryProvider repository = new RepositoryProvider();
            String consult = "select * from provider";
            List<Provider> providers = repository.OpenList(consult);
            addTable(providers);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Problem! " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSearchAllActionPerformed

    private void btnSearchEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEnableActionPerformed
        try{
            RepositoryProvider repository = new RepositoryProvider();
            String consult = "select * from provider where status = 1";
            List<Provider> providers = repository.OpenList(consult);
            addTable(providers);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Problem! " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSearchEnableActionPerformed

    private void btnSearchDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDisableActionPerformed
        try{
            RepositoryProvider repository = new RepositoryProvider();
            String consult = "select * from provider where status = 0";
            List<Provider> providers = repository.OpenList(consult);
            addTable(providers);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Problem! " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSearchDisableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchAll;
    private javax.swing.JButton btnSearchDisable;
    private javax.swing.JButton btnSearchEnable;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables
}
